name: 自动部署 # 步骤名称

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - README.md
    #   - LICENSE
    paths:
      - src/**
      - package.json

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm i

      - name: 编译构建
        run: npm run build

      # - name: SSH 命令删除旧文件
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.DEPLOY_KEY }}

      #     script: |
      #       rm -rf /home/suask/frontend/*

      # - name: 部署到服务器
      #   uses: wlixcc/SFTP-Deploy-Action@v1.0
      #   with:
      #     server: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     ssh_private_key: ${{ secrets.DEPLOY_KEY }}
      #     local_path: './dist/*'
      #     remote_path: '/home/suask/frontend/'

      - name: 部署到服务器
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: './dist/*'
          remote_path: '/home/suask/frontend/'
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
